dist: bionic


sudo: false

language:
    - python

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
  - pip install -r requirements.txt

os:
    - linux

script: './BUILDME'

notifications:
  email:
    on_success: never
    on_failure: change
